name: report_app
description: A simple Flutter app for capturing images, adding descriptions, and generating PDFs.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  camera: ^0.10.5+9
  pdfx: ^2.6.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  share_plus: ^10.0.2
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
